### ISSUE TITLE
Query API

### ISSUE THREAD

**Issue by rhysd** [rhysd/tinyjson#10]
Currently it is hard to access to nested elements. (`[]` operator panics when the key or index doesn't exist)

We need to consider some query API to 

- get nested values without panic
- check if some (nested) keys or indices are existing

API currently I'm thinking about:

```rust
let v: JsonValue = r#"[{"foo": true}]"#.parse().unwrap();

// Access to nested element
let found = v.query().child(0).child("foo").find();
assert_eq!(found, Some(&JsonValue::Boolean(true)));

// Check if key exists
assert!(v.query().child(0).exists());
assert!(!v.query().child(1).exists());
assert!(!v.query().child("foo").exists());

// Mutably access to nested element
let Some(found) = v.query_mut().child(0).child("foo").find() else { panic() };
*found = JsonValue::Number(10.0);
assert_eq!(v.stringify().unwrap(), "[{\"foo\":10}]");
```

**Comment by fkrauthan** [comment]
Hmm just out of curiosity: Couldn't you just add a new JsonValue (DoesNotExist, or NotFound) and when using index access and the value does not exist just always return that JsonValue?

so you could do 
```rust
let v: JsonValue = r#"[{"foo": true}]"#;
let key = v[0]["bar"]["test"];
if key.is_notfound() {
  panic!("Oh no");
}
```

**Comment by rhysd** [comment]
> Couldn't you just add a new JsonValue (DoesNotExist, or NotFound)

This means `JsonValue` no longer exactly represents JSON value. Users always must handle the `NotFound` variant even if `.parse()` returns success since `match` statement requires exhaustive pattern matching.

> when using index access and the value does not exist just always return that JsonValue?

Yeah, that's what I considered at first. Instead of adding a new variant, I thought returning `Option<JsonValue>` from index access.

`std::ops::Index` needs to return a reference.

```rust
pub trait Index<I> {
  type Output = ...;
  fn index(&'_ self, index: I) -> &'_ Self::Output; // Returns reference
}
```

So implementation like below is not possible.

```rust
#[derive(Clone, Copy)]
pub struct JsonQuery<'val>(Option<&'val JsonValue>);

impl<'val> Index<usize> for JsonQuery<'val> {
    type Output = Self;
    fn index(&self, idx: usize) -> &Self::Output {
        let inner = if let Some(JsonValue::Array(a)) = self.0 {
            a.get(idx)
        } else {
            None
        };
        &Self(inner) // Tries to return reference to local variable
    }
}
```

In addition, mutable access with `IndexMut` is more difficult since `&T` implements `Copy` but `&mut T` doesn't (mutable reference must be exclusive).

Other concern is API inconsistency. Standard containers like `Vec` or `HashMap` simply panics when trying to access to element which does not exist. So users usually expects similar behavior for `JsonValue` container. I agree that using `[]` is simpler, but providing it might be confusing.

**Comment by fkrauthan** [comment]
I understand the issue with JsonValue. However, the user in theory always has to handle the Option they get when calling get(). So if I do something like `let test: Option<&String> = v["test"]["test2"].get()` then I handle that Option which is ether a valid string (in case the full path exists) or a failed in case it has the meta JsonValue.

Alternative (and not sure if from API point of view its better) could be a `JsonPathValue` that gets returned for index operations that is a Enum that contains Value(JsonValue), NoValue as branches.

**Comment by rhysd** [comment]
> I understand the issue with JsonValue. However, the user in theory always has to handle the Option they get when calling get(). So if I do something like let test: Option<&String> = v["test"]["test2"].get() then I handle that Option which is ether a valid string (in case the full path exists) or a failed in case it has the meta JsonValue.

Yeah, I'm understanding your point. Users usually tests the value holds the inner value of type they want. JavaScript does it with `undefined` special value.
But I still want to stick to `JsonValue` representing exact JSON value. Adding variant like `Undefined` doesn't look very idiomatic Rust (usually we use `Option<JsonValue>` for this purpose).

> Alternative (and not sure if from API point of view its better) could be a JsonPathValue that gets returned for index operations that is a Enum that contains Value(JsonValue), NoValue as branches.

This idea is similar to mine above `struct JsonQuery<'val>(Option<&'val JsonValue>)`. And I tried to implement this with no luck.

```rust
enum JsonPathValue<'a> {
    Found(&'a JsonValue),
    NotFound,
}

impl Index<usize> for JsonValue {
    type Output = JsonPathValue<'a>; // ERROR: 'a is not accessible here
    fn index(&self, idx: usize) -> &Self::Output {
        if let JsonValue::Array(a) = self {
            &JsonPathValue::Found(a) // ERROR: Tries to return reference to local variable
        } else {
            &JsonPathValue::NotFound
        }
    }
}
```

**Comment by rhysd** [comment]
One advantage of my suggestion is extensibility. Currently there is only `.child()` method implemented in the query. But we can possibly implement other queries like `child_with`.

```rust
let v: JsonValue = r#"[-1, 0, 1]"#.parse().unwrap();
let num_greater_than_zero = v.query().child_with(|f: &f64| *f > 0.0).find();
assert_eq!(num_greater_than_zero, Some(&JsonValue::from(1.0)));
```
