### ISSUE TITLE
std::io::Read input

### ISSUE THREAD

**Issue by 89z** [rhysd/tinyjson#5]
If I have a reader input, for example coming from a HTTP request, can I JSON parse from the reader directly?

or do I have to read into a string first? It seems that for larger inputs, it could be more efficient to parse JSON from reader directly

**Comment by rhysd** [comment]
`JsonParser::new` takes `Iterator<Item=char>` so it assumes a sequence of UTF-8 characters. You would be able to do it by using a crate like [read_char](https://docs.rs/read_char/latest/read_char/).

**Comment by 89z** [comment]
I found a alternative:

https://docs.rs/serde_json/latest/serde_json/fn.from_reader.html

**Comment by rhysd** [comment]
Can we close this question?

**Comment by 89z** [comment]
I think the question should be closed, when the feature is implemented here, or if the maintainer refuse to implement
