### ISSUE TITLE
try_into fails inside function

### ISSUE THREAD

**Issue by 89z** [rhysd/tinyjson#6]
I saw this example in the README [1]:

~~~rust
// Move out inner value using try_into()
let num: f64 = json["num"].try_into().expect("Number value");
~~~

I need something similar inside a function. I tried this:

~~~rust
use tinyjson::JsonValue;

fn num(json: JsonValue) -> f64 {
   json["num"].try_into().unwrap_or_default()
}
~~~

but it does not work:

~~~
error[E0507]: cannot move out of index of `JsonValue`
 --> src\lib.rs:4:4
  |
4 |    json["num"].try_into().unwrap_or_default()
  |    ^^^^^^^^^^^ ---------- value moved due to this method call
  |    |
  |    move occurs because value has type `JsonValue`, which does not implement the `Copy` trait
  |
note: this function takes ownership of the receiver `self`, which moves value

For more information about this error, try `rustc --explain E0507`.
~~~

1. https://github.com/rhysd/tinyjson#access-to-json-value

**Comment by TheTechRobo** [comment]
try `.clone()`

**Comment by 89z** [comment]
Finally! I was going crazy on that. Thank you:

~~~rust
use tinyjson::JsonValue;

pub fn num(json: JsonValue) -> f64 {
   json["num"].clone().try_into().unwrap_or_default()
}
~~~

I will leave this open, as I think it a valid use case that should be documented.

**Comment by TheTechRobo** [comment]
It's also kind of annoying, since the line gets longer with `.clone().try_into()`

**Comment by 89z** [comment]
@TheTechRobo can you help me with another one? I am trying to do the same thing with this:

https://docs.rs/sj/latest/sj/enum.Value.html#method.by

but your trick doesnt work, it says the Error part doesnt satisfy Clone

**Comment by TheTechRobo** [comment]
¯\\\_(ツ)\_/¯

Never used that crate before.

**Comment by 89z** [comment]
Figured it out - it has a method that returns value instead of reference:

https://docs.rs/sj/latest/sj/enum.Value.html#method.take_by
