### ISSUE TITLE
as_string

### ISSUE THREAD

**Issue by 89z** [rhysd/tinyjson#8]
If you want to build an object, it might look like this:

~~~rust
use tinyjson::JsonValue;

fn main() {
   let value = JsonValue::Object([
      ("null".into(), JsonValue::Null),
      ("boolean".into(), JsonValue::Boolean(true)),
      ("number".into(), JsonValue::Number(1.0)),
      ("string".into(), JsonValue::String("one".into()))
   ].into());
   dbg!(value);
}
~~~

This is OK enough, but the String line could be better. I was thinking something like this:

~~~rust
use tinyjson::JsonValue;

fn as_string(v: &str) -> JsonValue {
   JsonValue::String(v.into())
}

fn main() {
   let value = JsonValue::Object([
      ("null".into(), JsonValue::Null),
      ("boolean".into(), JsonValue::Boolean(true)),
      ("number".into(), JsonValue::Number(1.0)),
      ("string".into(), as_string("one"))
   ].into());
   dbg!(value);
}
~~~

I was wondering if you would consider adding a function like this, or maybe some other idea to ease object creation. Thank you for great software you have written!

**Comment by 89z** [comment]
Another approach that might work, is an object builder:

~~~rust
fn main() -> Result<(), sj::Error> {
   let mut value = sj::object();
   value.insert("null", sj::Value::Null)?;
   value.insert("boolean", true)?;
   value.insert("number", 1)?;
   value.insert("string", "one")?;
   dbg!(value);
   Ok(())
}
~~~

https://docs.rs/sj/latest/sj/enum.Value.html#method.insert

**Comment by rhysd** [comment]
> I was wondering if you would consider adding a function like this

I don't think this is necessary. `JsonValue::String` is enough.

**Comment by 89z** [comment]
Thank you for the good software and fast response. In that case, I will just use the other crate, since it already has methods for easy object creation. Thanks again
